---
- name: create data directory
  file: path=/data state=directory mode=0755

- name: copy content to data directory
  copy: src=roles/edh-stack/files/ dest=/data owner=root group=root mode=0644

- name: create elasticsearch container
  docker_container:
    name: elasticsearch
    image: elasticsearch

- name: create kibana container
  docker_container:
    name: kibana
    image: kibana
    links:
      - "elasticsearch:elasticsearch"

- name: create nginx container
  docker_container:
    name: nginx
    image: nginx
    published_ports:
      - 80:80
    volumes:
      - /data:/usr/share/nginx/html:ro
