---
- name: create fluentd conf directory
  file: path=/data/fluentd/etc state=directory mode=0755

- name: create fluentd log directory
  file: path=/data/fluentd/log state=directory mode=0777

- name: create nginx directory
  file: path=/data/nginx state=directory mode=0755

- name: push fluentd content
  copy: src=roles/edh-stack/files/fluentd/etc/ dest=/data/fluentd/etc owner=root group=root mode=0644

- name: push nginx content
  copy: src=roles/edh-stack/files/nginx/ dest=/data/nginx owner=root group=root mode=0644

- name: create fluentd image
  docker_image:
    name: fluentd
    state: present
    path: roles/edh-stack/files/fluentd/

- name: create elasticsearch container
  docker_container:
    name: elasticsearch
    image: elasticsearch

- name: create fluentd container
  docker_container:
    name: fluentd
    image: fluentd
    links:
      - elasticsearch:elasticsearch
    published_ports:
      - 24224:24224
    volumes:
      - /data/fluentd/etc:/fluentd/etc
      - /data/fluentd/log:/fluentd/log

- name: create kibana container
  docker_container:
    name: kibana
    image: kibana
    links:
      - elasticsearch:elasticsearch
    env:
      NODE_OPTIONS: --max-old-space-size=300

- name: create nginx container
  docker_container:
    name: nginx
    image: nginx
    links:
      - kibana:kibana
    published_ports:
      - 80:80
      - 5601:5601
    volumes:
      - /data/nginx/html:/usr/share/nginx/html:ro
      - /data/nginx/conf.d:/etc/nginx/conf.d:ro
  