---
# Ansible entry point for applicaton and logging stack
# - apply the docker role to install and start the docker service
# - apply the edh-stack role to deploy and configure the stack services
- name: install docker to manage nginx, kibana and elasticsearch containers
  hosts: all

  roles:
    - docker
    - edh-stack